# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("background-color: rgb(24,24,26);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 32))
        self.top_bar.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.top_bar.setLineWidth(0)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toggle_menu = QtWidgets.QFrame(self.top_bar)
        self.toggle_menu.setMaximumSize(QtCore.QSize(70, 32))
        self.toggle_menu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.toggle_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.toggle_menu.setLineWidth(0)
        self.toggle_menu.setObjectName("toggle_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.toggle_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_menu = QtWidgets.QPushButton(self.toggle_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_menu.sizePolicy().hasHeightForWidth())
        self.btn_menu.setSizePolicy(sizePolicy)
        self.btn_menu.setMinimumSize(QtCore.QSize(45, 0))
        self.btn_menu.setMaximumSize(QtCore.QSize(45, 32))
        self.btn_menu.setStyleSheet("QPushButton:pressed {\n"
"    border-style: inset;\n"
"}")
        self.btn_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/menu_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(32, 32))
        self.btn_menu.setAutoDefault(False)
        self.btn_menu.setDefault(False)
        self.btn_menu.setFlat(True)
        self.btn_menu.setObjectName("btn_menu")
        self.verticalLayout_2.addWidget(self.btn_menu)
        self.horizontalLayout.addWidget(self.toggle_menu)
        self.frame = QtWidgets.QFrame(self.top_bar)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 32))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.content.setLineWidth(0)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slide_menu = QtWidgets.QFrame(self.content)
        self.slide_menu.setMinimumSize(QtCore.QSize(0, 300))
        self.slide_menu.setMaximumSize(QtCore.QSize(48, 1000))
        self.slide_menu.setStyleSheet("background-color: rgb(64, 64, 64);")
        self.slide_menu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.slide_menu.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.slide_menu.setLineWidth(0)
        self.slide_menu.setObjectName("slide_menu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.slide_menu)
        self.horizontalLayout_4.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.icons_frame = QtWidgets.QFrame(self.slide_menu)
        self.icons_frame.setMinimumSize(QtCore.QSize(0, 300))
        self.icons_frame.setMaximumSize(QtCore.QSize(46, 1000))
        self.icons_frame.setStyleSheet("background-color: rgb(38, 38, 38);")
        self.icons_frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.icons_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.icons_frame.setLineWidth(0)
        self.icons_frame.setObjectName("icons_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.icons_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_serial = QtWidgets.QPushButton(self.icons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_serial.sizePolicy().hasHeightForWidth())
        self.btn_serial.setSizePolicy(sizePolicy)
        self.btn_serial.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_serial.setAutoFillBackground(False)
        self.btn_serial.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(55, 55, 55);\n"
"    border-style: inset;\n"
"}")
        self.btn_serial.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/arduino_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_serial.setIcon(icon1)
        self.btn_serial.setIconSize(QtCore.QSize(32, 32))
        self.btn_serial.setCheckable(False)
        self.btn_serial.setChecked(False)
        self.btn_serial.setAutoDefault(False)
        self.btn_serial.setDefault(False)
        self.btn_serial.setFlat(True)
        self.btn_serial.setObjectName("btn_serial")
        self.verticalLayout_4.addWidget(self.btn_serial)
        self.btn_database = QtWidgets.QPushButton(self.icons_frame)
        self.btn_database.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_database.sizePolicy().hasHeightForWidth())
        self.btn_database.setSizePolicy(sizePolicy)
        self.btn_database.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_database.setAutoFillBackground(False)
        self.btn_database.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(55, 55, 55);\n"
"    border-style: inset;\n"
"}")
        self.btn_database.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/database_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_database.setIcon(icon2)
        self.btn_database.setIconSize(QtCore.QSize(32, 32))
        self.btn_database.setFlat(True)
        self.btn_database.setObjectName("btn_database")
        self.verticalLayout_4.addWidget(self.btn_database)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_4.addWidget(self.icons_frame)
        self.horizontalLayout_2.addWidget(self.slide_menu)
        self.frame_3 = QtWidgets.QFrame(self.content)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.page_widgets = QtWidgets.QStackedWidget(self.frame_3)
        self.page_widgets.setEnabled(True)
        self.page_widgets.setAutoFillBackground(False)
        self.page_widgets.setLineWidth(0)
        self.page_widgets.setObjectName("page_widgets")
        self.serial_page = QtWidgets.QWidget()
        self.serial_page.setObjectName("serial_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.serial_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.serial_page)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.serialInput = QtWidgets.QLineEdit(self.frame_2)
        self.serialInput.setMinimumSize(QtCore.QSize(0, 40))
        self.serialInput.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serialInput.setFont(font)
        self.serialInput.setAutoFillBackground(False)
        self.serialInput.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"padding-left: 10px;")
        self.serialInput.setFrame(True)
        self.serialInput.setCursorPosition(0)
        self.serialInput.setClearButtonEnabled(False)
        self.serialInput.setObjectName("serialInput")
        self.verticalLayout_6.addWidget(self.serialInput)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_4.setAutoFillBackground(False)
        self.frame_4.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"border-radius:20px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_4)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1146, 578))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.serialOutput = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialOutput.sizePolicy().hasHeightForWidth())
        self.serialOutput.setSizePolicy(sizePolicy)
        self.serialOutput.setMinimumSize(QtCore.QSize(0, 0))
        self.serialOutput.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.serialOutput.setFont(font)
        self.serialOutput.setAutoFillBackground(False)
        self.serialOutput.setStyleSheet("color: rgb(255, 255, 255);")
        self.serialOutput.setLineWidth(0)
        self.serialOutput.setText("")
        self.serialOutput.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.serialOutput.setObjectName("serialOutput")
        self.verticalLayout_7.addWidget(self.serialOutput)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.frame_4)
        self.verticalScrollBar.setMaximumSize(QtCore.QSize(20, 16777215))
        self.verticalScrollBar.setStyleSheet("QScrollBar::handle:vertical {\n"
"    background-color: rgb(30, 30, 30);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(97, 68, 223);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(72, 42, 204);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    background: rgb(40, 40, 40);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    background: rgb(40, 40, 40);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    background-color: rgb(40, 40, 40);\n"
"    border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_3.addWidget(self.verticalScrollBar)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.page_widgets.addWidget(self.serial_page)
        self.database_page = QtWidgets.QWidget()
        self.database_page.setObjectName("database_page")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.database_page)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.database_page)
        self.frame_5.setStyleSheet("background-color: rgb(48, 48, 48);\n"
"border-radius:20px")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_8.setLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tabelaUsuarios = QtWidgets.QTableWidget(self.frame_8)
        self.tabelaUsuarios.setMinimumSize(QtCore.QSize(550, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabelaUsuarios.setFont(font)
        self.tabelaUsuarios.setStyleSheet("QTableView::item:selected {\n"
"color: rgb(255, 255, 255);\n"
"background:rgb(54, 54, 54); \n"
"}\n"
"                           \n"
"QTableCornerButton::section { \n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 50, 50);\n"
"border: 1px outset rgb(18, 18, 18);\n"
"}\n"
"                           \n"
"QHeaderView::section { \n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 50, 50);\n"
"border: 1px outset rgb(18, 18, 18);\n"
"}\n"
"\n"
"QTableView{\n"
"    color: rgb(255, 255, 255);\n"
"    gridline-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QTableView::item{\n"
"    background: {color};\n"
"}")
        self.tabelaUsuarios.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tabelaUsuarios.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tabelaUsuarios.setLineWidth(0)
        self.tabelaUsuarios.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tabelaUsuarios.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.tabelaUsuarios.setCornerButtonEnabled(False)
        self.tabelaUsuarios.setObjectName("tabelaUsuarios")
        self.tabelaUsuarios.setColumnCount(3)
        self.tabelaUsuarios.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaUsuarios.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaUsuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaUsuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaUsuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaUsuarios.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaUsuarios.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaUsuarios.setItem(0, 2, item)
        self.tabelaUsuarios.horizontalHeader().setVisible(True)
        self.tabelaUsuarios.horizontalHeader().setCascadingSectionResizes(False)
        self.tabelaUsuarios.horizontalHeader().setHighlightSections(True)
        self.tabelaUsuarios.horizontalHeader().setStretchLastSection(False)
        self.tabelaUsuarios.verticalHeader().setVisible(True)
        self.tabelaUsuarios.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout_9.addWidget(self.tabelaUsuarios)
        self.scrollUsuarios = QtWidgets.QScrollBar(self.frame_8)
        self.scrollUsuarios.setMinimumSize(QtCore.QSize(20, 0))
        self.scrollUsuarios.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scrollUsuarios.setStyleSheet("QScrollBar::handle:vertical {\n"
"    background-color: rgb(30, 30, 30);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(97, 68, 223);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(72, 42, 204);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    background: rgb(40, 40, 40);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    background: rgb(40, 40, 40);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    background-color: rgb(40, 40, 40);\n"
"    border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}")
        self.scrollUsuarios.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.scrollUsuarios.setObjectName("scrollUsuarios")
        self.horizontalLayout_9.addWidget(self.scrollUsuarios)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabelaEventos = QtWidgets.QTableWidget(self.frame_7)
        self.tabelaEventos.setMinimumSize(QtCore.QSize(550, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabelaEventos.setFont(font)
        self.tabelaEventos.setStyleSheet("QTableView::item:selected {\n"
"color: rgb(255, 255, 255);\n"
"background:rgb(54, 54, 54); \n"
"}\n"
"                           \n"
"QTableCornerButton::section { \n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 50, 50);\n"
"border: 1px outset rgb(18, 18, 18);\n"
"}\n"
"                           \n"
"QHeaderView::section { \n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(50, 50, 50);\n"
"border: 1px outset rgb(18, 18, 18);\n"
"}\n"
"\n"
"QTableView{\n"
"    color: rgb(255, 255, 255);\n"
"    gridline-color: rgb(30, 30, 30);\n"
"}\n"
"\n"
"QTableView::item{\n"
"    background: {color};\n"
"}")
        self.tabelaEventos.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tabelaEventos.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tabelaEventos.setLineWidth(0)
        self.tabelaEventos.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tabelaEventos.setObjectName("tabelaEventos")
        self.tabelaEventos.setColumnCount(4)
        self.tabelaEventos.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaEventos.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaEventos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaEventos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaEventos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tabelaEventos.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_8.addWidget(self.tabelaEventos)
        self.scrollEventos = QtWidgets.QScrollBar(self.frame_7)
        self.scrollEventos.setMinimumSize(QtCore.QSize(20, 0))
        self.scrollEventos.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scrollEventos.setStyleSheet("QScrollBar::handle:vertical {\n"
"    background-color: rgb(30, 30, 30);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    background-color: rgb(97, 68, 223);\n"
"    border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {\n"
"    background-color: rgb(72, 42, 204);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    background: rgb(40, 40, 40);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    background: rgb(40, 40, 40);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    background-color: rgb(40, 40, 40);\n"
"    border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"     border-radius: 4px;\n"
"}")
        self.scrollEventos.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.scrollEventos.setObjectName("scrollEventos")
        self.horizontalLayout_8.addWidget(self.scrollEventos)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_5.addWidget(self.frame_7)
        self.horizontalLayout_7.addWidget(self.frame_5)
        self.page_widgets.addWidget(self.database_page)
        self.verticalLayout_3.addWidget(self.page_widgets)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.page_widgets.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadeira"))
        self.serialInput.setPlaceholderText(_translate("MainWindow", "Digite:"))
        self.tabelaUsuarios.setSortingEnabled(False)
        item = self.tabelaUsuarios.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabelaUsuarios.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.tabelaUsuarios.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Senha"))
        item = self.tabelaUsuarios.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Admin"))
        __sortingEnabled = self.tabelaUsuarios.isSortingEnabled()
        self.tabelaUsuarios.setSortingEnabled(False)
        item = self.tabelaUsuarios.item(0, 0)
        item.setText(_translate("MainWindow", "Victor"))
        item = self.tabelaUsuarios.item(0, 1)
        item.setText(_translate("MainWindow", "Arruda"))
        item = self.tabelaUsuarios.item(0, 2)
        item.setText(_translate("MainWindow", "1"))
        self.tabelaUsuarios.setSortingEnabled(__sortingEnabled)
        item = self.tabelaEventos.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabelaEventos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Data"))
        item = self.tabelaEventos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Horário"))
        item = self.tabelaEventos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Evento"))
        item = self.tabelaEventos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Usuário"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
